name: Terraform-Docs

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  documentation:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        name: Checkout source code

      - name: Run Terraform-Docs
        run: make test_documentation
